name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        sh instalation.sh
        chmod +x instalation.sh
        docker build -t devops_todo:latest .
        docker tag devops_todo:latest ${{ secrets.DOCKER_USERNAME }}/todo
        docker push ${{ secrets.DOCKER_USERNAME }}/todo

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Run installation script
      run: |
        chmod +x ./instalation.sh
        ./instalation.sh

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/todo:latest
        docker-compose down
        docker-compose up -d
        EOF
