name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t devops_todo:latest .
        docker tag devops_todo:latest ${{ secrets.DOCKER_USERNAME }}/dinesh359/todo:latest
        docker push devops_todo:latest

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/devops_todo:latest
        docker-compose down
        docker-compose up -d
        EOF
